### ISSUE TITLE
串口未找到出错

### ISSUE THREAD

**Issue by zchliu** [WangXuan95/FPGA-Gzip-compressor#2]
您好，我按照 readme 里面的步骤把工程新建好了，在跑 python 文件的时候发现了下面的报错
```
original data length = 524288 bytes
  0.  ttyS0  hwid=PNP0501
  1.  CP2108 Quad USB to UART Bridge Controller - CP2108 Interface 3  hwid=USB VID:PID=10C4:EA71 SER=40514E02D54EB08011E72A9E738F7EB LOCATION=1-4:1.3
  2.  CP2108 Quad USB to UART Bridge Controller - CP2108 Interface 2  hwid=USB VID:PID=10C4:EA71 SER=40514E02D54EB08011E72A9E738F7EB LOCATION=1-4:1.2
  3.  CP2108 Quad USB to UART Bridge Controller - CP2108 Interface 1  hwid=USB VID:PID=10C4:EA71 SER=40514E02D54EB08011E72A9E738F7EB LOCATION=1-4:1.1
  4.  CP2108 Quad USB to UART Bridge Controller - CP2108 Interface 0  hwid=USB VID:PID=10C4:EA71 SER=40514E02D54EB08011E72A9E738F7EB LOCATION=1-4:1.0
Please select a port (enter a number): 2
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: 'ttyUSB2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zchliu/work/FPGA-Gzip-compressor/Arty-example/python/fpga_uart_gz.py", line 127, in <module>
    gz_data, err_msg = GzipCompressUsePort(port_name, orig_data)
  File "/home/zchliu/work/FPGA-Gzip-compressor/Arty-example/python/fpga_uart_gz.py", line 53, in GzipCompressUsePort
    port = Serial(port_name, baudrate=115200, timeout=1.0)
  File "/root/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/root/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port ttyUSB2: [Errno 2] No such file or directory: 'ttyUSB2'
```
这看起来像是 serial 没有找到对应的文件目录导致的，我按照网上的解决办法，将 port 改成了本地目录以后跑通了
```
port = Serial("/dev/serial/by-id/usb-Silicon_Labs_CP2108_Quad_USB_to_UART_Bridge_Controller_40514E02D54EB08011E72A9E738F7EB-if02-port0", baudrate=115200, timeout=1.0)
    # try :
    #     port = Serial(port_name, baudrate=115200, timeout=1.0)
    # except :
    #     return None, '**error: Unable to open port %s' % port_name
```
但是，这似乎和程序查找串口然后再选择的功能不太一致，想问一下您有遇到这个问题吗？以及如何解决的呢？

系统：ubuntu 22.04
vivado：2022.2
开发板：zcu102

**Comment by WangXuan95** [comment]
你好，因为我用的 Windows ，指定串口号后，`listAndSelectPort()` 函数返回的是 COM 号字符串，比如 "COM4" ，然后直接传参给：
`port = Serial(port_name, baudrate=115200, timeout=1.0)` 
也就是 ：
`port = Serial(”COM4", baudrate=115200, timeout=1.0)`
就能成功打开 COM4 。

但在你的 Linux 上，`listAndSelectPort()` 函数返回的是字符串 "ttyUSB2" 。要打开这个串口，必须用绝对路径 "/dev/ttyUSB2" ，而不是 "ttyUSB2" 。也即：
`port = Serial("/dev/ttyUSB2", baudrate=115200, timeout=1.0)`
因此这里我还需要写一个判断系统类型，并决定是否要在前面加上 `/dev/` 的逻辑。或者干脆说明该程序只能适用于 Windows 。

另外，请问你那里跑出来的压缩文件都没问题吧？

**Comment by zchliu** [comment]
谢谢，明白了。我这里能够跑一个 .gz 文件出来，解压以后我用 vscode 进行比较以后没有发现什么错误，用 check_gz_file 也没有报错。实验的过程我写了一篇文章在知乎上面：https://zhuanlan.zhihu.com/p/633332670 。另外，这个 hex 文件是什么格式呀，我用文本打开以后显示了一团乱码，是只有这种格式才能被 uart 接收吗？

**Comment by WangXuan95** [comment]
hex 就是裸数据文件格式。里面是一个一个的字节，在 Windows 上可以用 Winhex 软件打开并查看，在 Linux 上可以用命令行工具 hexdump 工具查看。

实际上，所有的文件都是一个一个的字节构成的。用不同的程序打开它们，相当于用不同的方式解读这些字节，才能看到不一样的东西。例如一个 .jpg 图片文件也是一堆字节，用画图软件打开就能看到图片，用 Winhex 打开也会看到一堆乱码。

所有格式的文件都能被我的压缩程序压缩，比如输入以下命令来压缩 data.txt 文本文件：
`python fpga_uart_gz_file.py data.txt`
会得到 data.txt.gz 。把它解压后又会得到 data.txt

另外注意，待压缩的文件必须 ≥32 字节，否则我的 GZIP 压缩器会把它当作不值得压缩的数据而丢弃。

**Comment by zchliu** [comment]
明白了，谢谢！
